In [1]:
import datetime
import pandas as pd
from invest import Portfolio, Investment, Currency
from config import Config

In [2]:
invests = {}
for k, v in Config.FUNDS.items():
    pfls = [Portfolio(c, Config.STOCKS[c]) for c in v[1:]]
    invests[k] = Investment(k, v[0], pfls)

In [3]:
day = datetime.date.today()
df_cny = invests['cny'].portfolios[0]
df_hkd = invests['hkd'].portfolios[0]
df_usd = invests['hkd'].portfolios[1]

In [21]:
df_cny._trades.loc[['000001']]

,Name,Date,Transaction,Qty,Price,Commission,Tax,Broker,Cost
Symbol,,,,,,,,,
000001,平安银行,2016-12-30,BUY,5000,9.08,11.35,0.0,GJ-WJ,45411.35
000001,平安银行,2016-12-30,BUY,2000,9.08,5.00,0.0,GJ-WJ,18165.00
000001,平安银行,2017-01-16,BUY,3000,9.11,6.83,0.0,GJ-ZJW,27336.83
000001,平安银行,2017-04-19,BUY,2000,8.96,5.00,0.0,GJ-WJ,17925.00
000001,平安银行,2017-05-04,BUY,2000,8.72,5.00,0.0,GJ-ZJW,17445.00
000001,平安银行,2017-05-12,BUY,2000,8.86,5.00,0.0,GJ-WJ,17725.00
000001,平安银行,2017-05-22,BUY,2000,8.62,5.00,0.0,GJ-WJ,17245.00
000001,平安银行,2017-07-12,BUY,2000,10.36,5.18,0.0,GJ-WJ,20725.18
000001,平安银行,2017-12-06,SELL,-5000,13.12,19.50,65.6,GJ-WJ,65514.90